name: Manual Hello World

on:
  workflow_dispatch:

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello, World!"
      - name: Print Goodbye World      # Add this
        run: echo "Goodbye, World!"    # Add this

